tap "anomalyco/tap"
tap "can1357/tap"
tap "stablyai/orca", trusted: { casks: ["orca"] }
tap "steipete/tap", trusted: true
tap "xcodesorg/made", trusted: { formulae: ["xcodes"] }

brew "aria2"
brew "bat"
brew "btop"
brew "cliclick"
brew "cocoapods"
brew "eas-cli"
brew "eza"
brew "fastlane"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "kimi-code"
brew "libxcursor"
brew "mole"
brew "openspec"
brew "pi-coding-agent"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "vite-plus"
brew "watchman"
brew "xcodes"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "can1357/tap/omp", trusted: true

cask "android-studio"
cask "chatgpt"
cask "claude-code@latest"
cask "cloudflare-warp"
cask "codex"
cask "codexbar"
cask "cursor"
cask "cursor-cli"
cask "expo-orbit"
cask "finicky"
cask "font-maple-mono-nf"
cask "ghostty"
cask "karabiner-elements"
cask "logi-options+"
cask "openkey"
cask "proxyman"
cask "raycast"
cask "slack"
cask "tailscale-app"
cask "telegram"
cask "visual-studio-code"
cask "zcode"
cask "zed"
cask "zen"
cask "zulu@17"

vscode "ai-engineer-coach.ai-engineer-coach"
vscode "astro-build.astro-vscode"
vscode "blazejkustra.react-compiler-marker"
vscode "bradlc.vscode-tailwindcss"
vscode "chakrounanas.turbo-console-log"
vscode "dbaeumer.vscode-eslint"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "expo.vscode-expo-tools"
vscode "oxc.oxc-vscode"
vscode "redhat.vscode-yaml"
vscode "streetsidesoftware.code-spell-checker"
vscode "tamasfe.even-better-toml"
vscode "usernamehw.errorlens"
vscode "zhuangtongfa.material-theme"

npm "@stripe/cli"
npm "@xai-official/grok"
npm "9router"
npm "better-sqlite3"
npm "vercel"
